name: omarchy_calculator
description: "The official Omarchy calculator"
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  calc_engine:
    path: ../calc_engine/
  cupertino_icons: ^1.0.8
  flutter_omarchy: ^0.1.12
  intl: ^0.20.2
  yaml: ^3.1.3
  path_provider: ^2.1.5
  dart_mappable: ^4.6.0
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.6.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: CaskaydiaMono Nerd Font Mono
      fonts:
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Regular.ttf
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Bold.ttf
          weight: 700
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Italic.ttf
          style: italic
