name: omarchy_calculator
description: "The official Omarchy calculator"
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  calc_engine:
    path: ../calc_engine/
  cupertino_icons: ^1.0.8
  flutter_omarchy: ^0.1.8
  intl: ^0.20.2
  yaml: ^3.1.3
  path_provider: ^2.1.5
  dart_mappable: ^4.6.0
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.6.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: CaskaydiaMono Nerd Font Mono
      fonts:
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Regular.ttf
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Bold.ttf
          weight: 700
        - asset: test/fonts/CaskaydiaMonoNerdFontMono-Italic.ttf
          style: italic
