name: Development

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runs-on: ubuntu-24.04
          #- arch: arm64
          #  runs-on: ubuntu-24.04-arm

    name: linux-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          cd packages/omarchy_calculator
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev curl git

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter init
        run: |
          cd packages/omarchy_calculator
          flutter --version
          flutter doctor -v
          flutter config --enable-linux-desktop
          flutter pub get

      - name: Flutter tests
        run: |
          cd packages/omarchy_calculator
          flutter test --dart-define="ignore-goldens=true"

      - name: Build Linux (release)
        run: |
          cd packages/omarchy_calculator
          flutter build linux --release

      - name: Create archive
        run: |
          cd packages/omarchy_calculator/build/linux/${{ matrix.arch }}/release/bundle/
          tar -czf omarchy_calculator-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz omarchy_calculator
          mv omarchy_calculator-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz ../../../../../../../

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: omarchy_calculator-${{ matrix.arch }}
          path: omarchy_calculator-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz
