name: Release (x64 + arm64)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    name: linux-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev curl git

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Fetch packages
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Linux (release)
        run: flutter build linux --release

      - name: Upload artifact (bundle)
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-${{ matrix.arch }}
          path: build/linux/*/release/bundle/

      - name: Upload binary artifact
        if: ${{ always() && hashFiles('out/app-*') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-binary-${{ matrix.arch }}
          path: out/app-${{ matrix.arch }}

